import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class MatchFrame extends javax.swing.JFrame
{
    private Clobber game;
    private Thread thread;
    private Match match;

    public MatchFrame(Clobber game, List<ClobberBot> bots)
    {
        this.game = game;
        initComponents();
		final KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
		manager.addKeyEventDispatcher(
				new KeyEventDispatcher() {

			@Override
			public boolean dispatchKeyEvent(KeyEvent e)
			{
				manager.redispatchEvent(panel, e);
				return false;
			}
		});
        this.match = new Match(game, bots, new QueensPlacement(), panel);
    }

    public void start()
    {
        thread = new Thread((Runnable) match);
        thread.start();
    }

    private class MatchRunnerPanel extends JPanel
    {
        final JFrame window;
        public MatchRunnerPanel(JFrame window)
        {
            this.window = window;
            setPreferredSize(new Dimension(game._width, game._height));
            setSize(game._width, game._height);
        }

        @Override
        protected void paintComponent(Graphics g)
        {
            if (match.isFinished())
            {
                match.printResults();
                window.dispose();
            }

            g.setColor(Color.BLACK);
            g.fillRect(0, 0, game._width, game._height);
            for (int x = 0; x < match.bots.size(); x++)
            {
                BotManager cbm = match.bots.get(x);
                cbm.getBot().drawMe(g, cbm.pos);
            }
            for (int x = match.bullets.size() - 1; x >= 0; x--)
            {
                Bullet bul = match.bullets.get(x);
                int i = (int) (bul.pos.getX());
                int j = (int) (bul.pos.getY());
                int n = i - game.BULLET_GIRTH / 2 - 1;
                int m = j - game.BULLET_GIRTH / 2 - 1;
                g.setColor(Color.green);
                g.fillOval(n, m, game.BULLET_GIRTH, game.BULLET_GIRTH);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new MatchRunnerPanel(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        thread.interrupt();
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
